### ISSUE TITLE
this client cant work!

### ISSUE THREAD

**Issue by logemann** [AnomalyInnovations/sigV4Client#1]
Hi,

just tried your class and it has at least two bugs. Doesnt work w/o modifications! I can pinpoint a few:

198: const path = awsSigV4Client.pathComponent + request.path;
needs to be:
198; const path = awsSigV4Client.pathComponent;

268: Must be part of the signing process and needs to be moved more to the top.

**Comment by jayair** [comment]
@logemann We talk about using this in this chapter here - https://serverless-stack.com/chapters/connect-to-api-gateway-with-iam-auth.html.

And we have had this in production for quite a while. For line 198, `request.path` is being used and can be passed in when you invoke it. For line 268, I'm not sure what you mean.

Can you show me the errors you are running into?

**Comment by logemann** [comment]
awsSigV4Client.pathComponent + request.path results in
/dev/api/createuser/http://.....

client call looks like this:

```
const signedRequest = sigV4Client.newClient({
      accessKey: AWS.config.credentials.accessKeyId,
      secretKey: AWS.config.credentials.secretAccessKey,
      sessionToken: AWS.config.credentials.sessionToken,
      region: "eu-central-1",
      endpoint: "https://xxxxx.execute-api.eu-central-1.amazonaws.com/dev/api/createuser"
}).signRequest({
      method: "post",
      path: "https://xxxxxx.execute-api.eu-central-1.amazonaws.com/dev/api/createuser",
      headers: {},
      queryParams: {},
});
```

For 268: If you use a sessionToken, this must be signed too and with your code, you dont sign that.

**Comment by jayair** [comment]
@logemann This isn't well documented because it was a part of the tutorial. But `path` is relative to the `endpoint`.

And in the examples we do use `sessionToken` and line 268 doesn't need to be moved up for it to work. I'm not sure what error you are seeing. But we are using this exact setup in production and in the past versions of the tutorial.

**Comment by logemann** [comment]
whatever. The path got constructed wrongly with the caller mentioned in my post and with your code from github. 

Also in your code sessionToken wont get signed in the Authorisation header which is also obvious because the signing happens a few lines above. You just put the sessionToken in the X_AMZ_SECURITY_TOKEN header but you dont sign it.

Perhaps you dont use sessionTokens or its in fact not needed to sign it (Postman does it though) but either one of the two issues broke the call to AWS or both of them.

**Comment by jayair** [comment]
@logemann What type of authentication are you using for your API?

Btw, this client is simply a part of AWS's own sigV4Client that ships with their SDK. There is very little modification to the actual logic.

**Comment by logemann** [comment]
I know that this client is a variant of AWS api gateway SDK which you can download. But you modified the path portion which made the problem for me. I rewrote this thing to be a class btw. Didnt touch the content very much apart from two parts i mentioned. I can put that on github if you like.

What do you mean which type auf Auth? You mean the API GW authorizer? This is AWS_IAM.

**Comment by jayair** [comment]
@logemann Yeah feel free to put it up and link to it here. We have moved on to using AWS Amplify instead of this client. But if I can test the case that is causing the issue, then I'll update it here as well.
