### ISSUE TITLE
Invalid signature with custom headers (e.g. X-Tenant-Id)

### ISSUE THREAD

**Issue by MEGApixel23** [AnomalyInnovations/sigV4Client#2]
Hi there!

When I add custom header ```X-Tenant-Id``` AWS returns the following error:

```json
{
    "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been..."
}
```

UPD: If the header is passed in a lower case: ```x-tenant-id``` the signature is valid and a request works.

What should one do if the custom spelling of a header is needed?

**Comment by jayair** [comment]
Hi there, we aren't really using this package anymore since Amplify handles the signature generation for us. What are you using this for?

**Comment by MEGApixel23** [comment]
@jayair Thank you for the answer!

I'm working on this project with a lot of legacy dependencies. This package is used for signing requests to AWS API Gateway with Cognito credentials. I'm not really sure how the whole schema works but will be really grateful if you could point out what's a modern way to do signing requests now. Thanks!

**Comment by jayair** [comment]
We switched to using Amplify, it does this for you — https://serverless-stack.com/chapters/configure-aws-amplify.html

Would that work for you?
